version: "3"
services:
    mysql:
        image: mysql:8.0
        container_name: holodlab_mysql
        environment:
            MYSQL_DATABASE: holodlab_admin
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: holodlab
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        image: redis:alpine
        container_name: holodlab_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
volumes:
    mysql_data:
    redis_data:
